#!/usr/bin/env python
'''
Run script using:
$ tests/run

Add -v flag for unittests verbosity level 2.
Add --coverage flag to create a coverage report.
Add --profiler flag to create a cProfile report.
'''

import sys
import os

base_dir = os.getcwd()
sys.path.insert(0, base_dir)

from unittest import TestSuite, TextTestRunner
from unittest import defaultTestLoader

import cProfile, pstats
import coverage

import filtering_test
import degradation_test
import aggregation_test
import normalization_pvwatts_test
import normalization_sapm_test
import clearsky_temperature_test


if __name__ == "__main__":
    if '-v' in sys.argv:
        verbosity = 2
    else:
        verbosity = 1

    suite = TestSuite()
    dtl = defaultTestLoader
    suite.addTests(dtl.loadTestsFromModule(filtering_test))
    suite.addTests(dtl.loadTestsFromModule(degradation_test))
    suite.addTests(dtl.loadTestsFromModule(aggregation_test))
    suite.addTests(dtl.loadTestsFromModule(normalization_pvwatts_test))
    suite.addTests(dtl.loadTestsFromModule(normalization_sapm_test))
    suite.addTests(dtl.loadTestsFromModule(clearsky_temperature_test))
    runner = TextTestRunner(verbosity=verbosity)

    if '--profiler' in sys.argv:
        profiler = cProfile.Profile()
        profiler.enable()
        profiler_report = True
    else:
        profiler_report = False

    if '--coverage' in sys.argv:
        cov = coverage.Coverage()
        cov.start()
        coverage_report = True
    else:
        coverage_report = False

    result = runner.run(suite)

    if coverage_report:
        cov.stop()
        cov.save()
        include = ['rdtools/*']
        with open('test_coverage.log', 'w') as log:
            cov.report(show_missing=True, include=include, file=log)

    if profiler_report:
        profiler.disable()
        sortby = 'cumulative'
        with open('test_profiler.log', 'w') as log:
            ps = pstats.Stats(profiler, stream=log).sort_stats(sortby)
            ps.print_stats('rdtools/rdtools/')

    sys.exit(len(result.errors) + len(result.failures))
