name: notebook-check

on: [pull_request, push]

jobs:
  notebook-check:
    strategy:
      matrix:
        notebook-file: [
          'system_availability_example.ipynb',
          'TrendAnalysis_example_pvdaq4.ipynb',
          'degradation_and_soiling_example_pvdaq_4.ipynb'
          # can't run the DKASC notebook here because it requires pre-downloaded data
        ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install test environment
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt -r docs/notebook_requirements.txt .[test]

    # test notebook using pytest-notebook; see setup.cfg for configuration
    - name: pytest-notebook 
      run: | 
        pytest --nb-test-files --nb-exec-timeout=500 docs/${{ matrix.notebook-file }}
