name: notebook-check

on: [pull_request, push]

jobs:
  notebook-check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        env: [
          '-r requirements.txt -r docs/notebook_requirements.txt .[test]',
        ]
        notebook: [
          'TrendAnalysis_example_pvdaq4.ipynb',
          'degradation_and_soiling_example_pvdaq_4.ipynb',
          'system_availability_example.ipynb',
          # we can't download the data file automatically, so skip the DKASC notebook
          # 'degradation_and_soiling_example.ipynb',
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ${{ matrix.env }}
      run: |
        python -m pip install --upgrade pip wheel
        pip install ${{ matrix.env }}
        pip install pytest-notebook==0.6.1
    - name: Test with pytest-notebook ${{ matrix.env }}
      run: |  # see setup.cfg for pytest-notebook configuration
        pytest --nb-test-files --nb-exec-timeout=500 docs/${{ matrix.notebook }}
