name: requirements

on: [pull_request, push]

jobs:
  requirements:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install notebook environment
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt -r docs/notebook_requirements.txt
