name: requirements

on:
  push:
  pull_request:


jobs:
  requirements:
    fail-fast: false  # don't cancel other matrix jobs when one fails
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install notebook environment
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt -r docs/notebook_requirements.txt
    - name: Check installed packages against requirements files
      run: |
        python .github/workflows/validate_requirements_versus_installed.py
