name: requirements

on:
  push:
    branches:
    - master
    - development
  pull_request:


jobs:
  requirements:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install notebook environment
      run: |
        python -m pip install --upgrade pip wheel
        pip install --timeout=300 -r requirements.txt -r docs/notebook_requirements.txt
